"use client";
import React, { useState } from "react";
import jsPDF from "jspdf";
import { FaDownload, FaSpinner } from "react-icons/fa";

const CourseCertificate = ({ courseName, userName, totalChapters }) => {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = () => {
    setDownloading(true);

    // 1. Create PDF Instance (Landscape, A4)
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    // --- DRAWING THE CERTIFICATE PROGRAMMATICALLY ---

    // 2. Background Color
    doc.setFillColor(255, 252, 245); // Cream/Off-white background
    doc.rect(0, 0, 297, 210, "F");

    // 3. Ornamental Border
    doc.setLineWidth(2);
    doc.setDrawColor(200, 150, 50); // Gold/Orange color
    doc.rect(10, 10, 277, 190); // Outer Border

    doc.setLineWidth(1);
    doc.setDrawColor(50, 50, 50); // Dark Gray
    doc.rect(15, 15, 267, 180); // Inner Border

    // 4. Header Text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(30);
    doc.setTextColor(50, 50, 50);
    doc.text("CERTIFICATE OF COMPLETION", 148.5, 50, { align: "center" });

    // 5. "Presented To"
    doc.setFont("helvetica", "normal");
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text("This certificate is proudly presented to", 148.5, 70, { align: "center" });

    // 6. User Name (Big & Purple)
    doc.setFont("times", "bolditalic");
    doc.setFontSize(40);
    doc.setTextColor(126, 34, 206); // Purple color
    doc.text(userName || "Student Name", 148.5, 95, { align: "center" });

    // Underline Name
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(70, 98, 227, 98);

    // 7. "For Completing"
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.text("For successfully completing the course:", 148.5, 115, { align: "center" });

    // 8. Course Name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(50, 50, 50);
    
    // Handle long course names by splitting
    const splitTitle = doc.splitTextToSize(courseName, 200);
    doc.text(splitTitle, 148.5, 135, { align: "center" });

    // 9. Footer Info (Date & Signature)
    const dateY = 175;
    
    // Date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 60, dateY);
    doc.line(40, dateY + 2, 100, dateY + 2); // Line

    // Signature
    doc.setFont("times", "italic");
    doc.setFontSize(20);
    doc.text("Sarika", 230, dateY - 5, { align: "center" }); // Fake Signature
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Instructor Signature", 230, dateY + 5, { align: "center" });
    doc.line(190, dateY + 2, 270, dateY + 2); // Line

    // 10. Gold Seal (Visual Circle)
    doc.setFillColor(255, 215, 0); // Gold
    doc.circle(148.5, 170, 12, "F");
    doc.setFontSize(8);
    doc.setTextColor(100, 70, 0);
    doc.text("VERIFIED", 148.5, 172, { align: "center" });

    // 11. Save
    doc.save(`${courseName.replace(/\s+/g, "_")}_Certificate.pdf`);
    setDownloading(false);
  };

  return (
    <div className="flex flex-col items-center gap-5">
      {/* --- VISUAL PREVIEW (HTML/CSS) --- */}
      {/* This is just what the user SEES on screen. The PDF is generated by the function above. */}
      <div className="overflow-x-auto w-full flex justify-center">
        <div 
            className="w-[800px] h-[600px] bg-[#fffcf5] relative border-[10px] border-double border-gray-800 p-10 shadow-2xl flex flex-col items-center justify-center text-center select-none"
            style={{ fontFamily: "'Times New Roman', serif" }} 
        >
            {/* Ornamental Borders */}
            <div className="absolute top-4 left-4 right-4 bottom-4 border-2 border-orange-400"></div>
            <div className="absolute top-2 left-2 right-2 bottom-2 border border-gray-800"></div>

            {/* Header */}
            <div className="mb-2">
                <h2 className="text-2xl uppercase tracking-[0.3em] text-gray-500 font-sans font-bold">Certificate of Completion</h2>
            </div>

            {/* Main Title */}
            <h1 className="text-6xl font-bold text-gray-900 mt-4 mb-2 italic">
                Course Achievement
            </h1>

            <p className="text-lg text-gray-600 mt-4">This certificate is proudly presented to</p>

            {/* User Name */}
            <h2 className="text-4xl font-bold text-purple-700 border-b-2 border-gray-300 pb-2 px-10 mt-2 min-w-[400px]">
                {userName || "John Doe"}
            </h2>

            <p className="text-lg text-gray-600 mt-6">
                For successfully completing the comprehensive course curriculum of
            </p>

            {/* Course Name */}
            <h3 className="text-3xl font-bold text-gray-800 mt-2 mb-8 max-w-2xl leading-tight">
                {courseName}
            </h3>

            {/* Details Row */}
            <div className="flex justify-between w-full px-20 mt-8 items-end">
                
                {/* Date */}
                <div className="flex flex-col items-center">
                    <p className="text-lg font-bold border-b border-gray-400 w-32 pb-1">{new Date().toLocaleDateString()}</p>
                    <p className="text-xs text-gray-500 uppercase mt-1">Date</p>
                </div>

                {/* Gold Seal */}
                <div className="relative">
                    <div className="w-24 h-24 bg-yellow-400 rounded-full flex items-center justify-center shadow-lg border-4 border-yellow-600">
                        <div className="w-20 h-20 border-2 border-dashed border-yellow-700 rounded-full flex items-center justify-center">
                            <span className="text-yellow-800 font-bold text-xs text-center leading-tight">
                                OFFICIAL<br/>CERTIFIED<br/>COURSE
                            </span>
                        </div>
                    </div>
                </div>

                {/* Signature */}
                <div className="flex flex-col items-center">
                    <p className="text-2xl text-gray-800 italic" style={{fontFamily: 'cursive'}}>Sarika</p>
                    <div className="border-b border-gray-400 w-40"></div>
                    <p className="text-xs text-gray-500 uppercase mt-1">Instructor Signature</p>
                </div>
            </div>
        </div>
      </div>

      {/* --- DOWNLOAD BUTTON --- */}
      <button 
        onClick={handleDownload}
        disabled={downloading}
        className="mt-6 bg-gradient-to-r from-purple-600 to-indigo-600 text-white px-8 py-3 rounded-full font-bold shadow-lg hover:shadow-xl hover:scale-105 transition-all flex items-center gap-3"
      >
        {downloading ? <FaSpinner className="animate-spin"/> : <FaDownload />}
        {downloading ? "Generating PDF..." : "Download Official Certificate"}
      </button>
    </div>
  );
};

export default CourseCertificate;